<h1> Introduction TensorFlow </h1>

'A tensor is a generalization of vectors and matrices to potentially higher dimentions. Internally, TensorFlow represents tensors as n-dimentionals arrays of datatypes.' (https://www.tensorflow.org/guide/tensor)

Tensorsd are the main object that are passed around manupulate throught the program. Each tensor represents a partialy defined computing that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related.

Each tensor has a data type and a shape

<b>Data Types Include </b>: float32, int32, string and others.

<b> Shape </b>: Represents the dimension of data.


<h3> Creating Tensors </h3>
Below is an example of how to create some different tensors.

In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.12.1


In [2]:
string = tf.Variable('this is a string', tf.string)
number = tf.Variable( 324, tf.int16  )
floating = tf.Variable( 31.1416, tf.float64 )

<h3> Rank/Degree of Tensors </h3>
Another word for rank is degree, these terms simply mean the numbers of dimensions involved in the tensor. What we create above is a tensor of rank 0, also known as a scalar.

Now, will create some tensors of higher degress/rank

In [3]:
rank1_tensor = tf.Variable( ['test','ok', 'Tim'], tf.string  )
rank2_tensor = tf.Variable( [['test','ok', 'Tim'], ['test','deploy', 'Tim']], tf.string  ) 
#Rank 2 because we have a list inside a list

To determine the rank of a tensor we can call the fllowing method

In [4]:
tf.rank( rank2_tensor )

<tf.Tensor: shape=(), dtype=int32, numpy=2>

<h3> Tensor Shapes </h3>
Now that we've talked about of ranks of tensors it's time to talk about the shape. The shape is simply the amount of elemts that exist in each dimension. TensorFlow will try to determine but sometimes is unknown.

In [5]:
rank2_tensor.shape #2 Lists with 3 elements.

TensorShape([2, 3])

<h3> Changing shape </h3>

The number of elemnts of a tensor is the productt of the sizes of all its shape.

In [6]:
tensor1 = tf.ones([1,2,3])  #Creates a shape [1,2,3] tensor full of ones
print(tensor1) 
tensor2 = tf.reshape(tensor1, [2,3,1] ) # reshape existing data to shape [2,3,1]
print(tensor2)
tensor3 = tf.reshape(tensor2, [3,-1]) #-1 tells the tensor to calculate the size of the dimentions in that place
print(tensor3)                        # this will reshape tensor to [3,2]


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


<h3> Types of Tensors </h3>

Before we go far I will mention that are three different types of tensors. 

<ol>
    <li> Vaiable </li>
    <li> Constant </li>
    <li> Placeholder </li>
    <li> SparceTensor </li>
</ol> 

With the exeption of Variable of all these tensors are inmutable, meaning their value may not change during execution. 

<h3> Evaluating Tensors </h3>

There will be sometimes throught this guide that we need to evaluate a tensor. In other words, gets its value. Since tensorsd represnts partially complete computation, we will need to run what's a session to evaluate the tensor.

There are many different ways to achieve this but I will note the simplest way below.

In [12]:
with tf.compat.v1.Session() as sess:
  constant = tf.constant([1, 2, 3])
  tft = constant*constant
  print(tft.eval())

[1 4 9]


In [ ]:
t = tf.zeros([5,5,5,5])
t = tf.reshape(t, [625])


<tf.Tensor 'zeros:0' shape=(5, 5, 5, 5) dtype=float32>

In the code above we evaluated the tensor variable that was stored in the default graph. It is possible to create our own separate graphs but for now we will stick with the default.

<h3> Sources </h3>

https://www.tensorflow.org/api_docs/python/tf/Tensor
https://stackoverflow.com/questions/58958713/evaluate-a-tensor-in-deferred-mode-in-tensorflow-2